access_key: ASIA3OH63NLGOBZ6XP7D
secret_key: KambVfIr64kpcOomjLdNOD65TuIzwNVYDbNRPpk1
session_token: FwoGZXIvYXdzEJH//////////wEaDD74p/FBzcLhkXiesSK+AQw8w5bhYCHLXS2PvgptBi73mzQKrLjtEa0jxgHF/+IYggkc6A8hLzAjZ0HnHkfZRVmfQQndXd3Do0jYXq2UOkWy61kVEOKrnVlVE+7zaZSRuSIFWhZwgdjWoKx7lKBeh+6503BqRCMVzY+I5nhLWhre5+3fpdsyaYcflfmog